// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        CData/*0:0*/ ChipInterface__DOT__clk10;
        VL_OUT8(led_data,0,0);
        VL_OUT8(led,7,0);
        VL_OUT8(SDI,0,0);
        VL_OUT8(SPC,0,0);
        VL_OUT8(CS,0,0);
        VL_IN8(SDO,0,0);
        VL_IN8(btn_left,0,0);
        VL_IN8(btn_right,0,0);
        VL_IN8(btn_up,0,0);
        VL_IN8(btn_down,0,0);
        VL_IN8(rst_n,0,0);
        CData/*0:0*/ ChipInterface__DOT__led_data;
        CData/*7:0*/ ChipInterface__DOT__led;
        CData/*0:0*/ ChipInterface__DOT__SDI;
        CData/*0:0*/ ChipInterface__DOT__SPC;
        CData/*0:0*/ ChipInterface__DOT__CS;
        CData/*0:0*/ ChipInterface__DOT__SDO;
        CData/*0:0*/ ChipInterface__DOT__btn_left;
        CData/*0:0*/ ChipInterface__DOT__btn_right;
        CData/*0:0*/ ChipInterface__DOT__btn_up;
        CData/*0:0*/ ChipInterface__DOT__btn_down;
        CData/*0:0*/ ChipInterface__DOT__rst_n;
        CData/*0:0*/ ChipInterface__DOT__clk;
        CData/*0:0*/ ChipInterface__DOT__reset;
        CData/*0:0*/ ChipInterface__DOT__locked;
        CData/*0:0*/ ChipInterface__DOT__toggle;
        CData/*0:0*/ ChipInterface__DOT__led_module__DOT__clock;
        CData/*0:0*/ ChipInterface__DOT__led_module__DOT__reset;
        CData/*0:0*/ ChipInterface__DOT__led_module__DOT__o_out;
        CData/*1:0*/ ChipInterface__DOT__led_module__DOT__frame_idx;
        CData/*0:0*/ ChipInterface__DOT__led_module__DOT__update;
        CData/*0:0*/ ChipInterface__DOT__led_module__DOT__busy;
        CData/*0:0*/ ChipInterface__DOT__led_module__DOT__in_bounds;
        CData/*0:0*/ ChipInterface__DOT__led_module__DOT__done;
        CData/*0:0*/ ChipInterface__DOT__led_module__DOT__ws__DOT__o_out;
        CData/*0:0*/ ChipInterface__DOT__led_module__DOT__ws__DOT__busy;
        CData/*0:0*/ ChipInterface__DOT__led_module__DOT__ws__DOT__update;
        CData/*0:0*/ ChipInterface__DOT__led_module__DOT__ws__DOT__clock;
        CData/*0:0*/ ChipInterface__DOT__led_module__DOT__ws__DOT__reset;
        CData/*5:0*/ ChipInterface__DOT__led_module__DOT__ws__DOT__bit_index;
        CData/*6:0*/ ChipInterface__DOT__led_module__DOT__ws__DOT__current_bit_index;
        CData/*0:0*/ ChipInterface__DOT__led_module__DOT__ws__DOT__refresh;
        CData/*0:0*/ ChipInterface__DOT__led_module__DOT__ws__DOT__cur_bit_dat;
        CData/*0:0*/ ChipInterface__DOT__sensor__DOT__reset;
        CData/*0:0*/ ChipInterface__DOT__sensor__DOT__SDO;
        CData/*0:0*/ ChipInterface__DOT__sensor__DOT__clk;
        CData/*0:0*/ ChipInterface__DOT__sensor__DOT__SPC;
        CData/*0:0*/ ChipInterface__DOT__sensor__DOT__CS;
        CData/*0:0*/ ChipInterface__DOT__sensor__DOT__SDI;
        CData/*4:0*/ ChipInterface__DOT__sensor__DOT__curr_state;
        CData/*4:0*/ ChipInterface__DOT__sensor__DOT__next_state;
        CData/*7:0*/ ChipInterface__DOT__sensor__DOT__addr;
        CData/*7:0*/ ChipInterface__DOT__sensor__DOT__wdata;
        CData/*7:0*/ ChipInterface__DOT__sensor__DOT__rdata;
        CData/*0:0*/ ChipInterface__DOT__sensor__DOT__read;
        CData/*0:0*/ ChipInterface__DOT__sensor__DOT__enable;
        CData/*0:0*/ ChipInterface__DOT__sensor__DOT__done;
        CData/*0:0*/ ChipInterface__DOT__sensor__DOT__clear;
        CData/*7:0*/ ChipInterface__DOT__sensor__DOT__spi_internal__DOT__addr;
        CData/*7:0*/ ChipInterface__DOT__sensor__DOT__spi_internal__DOT__wdata;
        CData/*0:0*/ ChipInterface__DOT__sensor__DOT__spi_internal__DOT__read;
        CData/*0:0*/ ChipInterface__DOT__sensor__DOT__spi_internal__DOT__clk;
    };
    struct {
        CData/*0:0*/ ChipInterface__DOT__sensor__DOT__spi_internal__DOT__enable;
        CData/*0:0*/ ChipInterface__DOT__sensor__DOT__spi_internal__DOT__reset;
        CData/*0:0*/ ChipInterface__DOT__sensor__DOT__spi_internal__DOT__SDO;
        CData/*0:0*/ ChipInterface__DOT__sensor__DOT__spi_internal__DOT__SPC;
        CData/*0:0*/ ChipInterface__DOT__sensor__DOT__spi_internal__DOT__CS;
        CData/*0:0*/ ChipInterface__DOT__sensor__DOT__spi_internal__DOT__SDI;
        CData/*7:0*/ ChipInterface__DOT__sensor__DOT__spi_internal__DOT__rdata;
        CData/*0:0*/ ChipInterface__DOT__sensor__DOT__spi_internal__DOT__done;
        CData/*5:0*/ ChipInterface__DOT__sensor__DOT__spi_internal__DOT__curr_state;
        CData/*5:0*/ ChipInterface__DOT__sensor__DOT__spi_internal__DOT__next_state;
        CData/*0:0*/ ChipInterface__DOT__sensor__DOT__wait_time__DOT__clock;
        CData/*0:0*/ ChipInterface__DOT__sensor__DOT__wait_time__DOT__clear;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__clk;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__reset;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__btn_left;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__btn_right;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__btn_up;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__btn_down;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__clear;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__btn_left;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__btn_right;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__btn_up;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__btn_down;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__clk;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__reset;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__clear;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__counter__DOT__clock;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__counter__DOT__clear;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__btn_left;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__btn_right;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__btn_up;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__btn_down;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__clk;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__reset;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__clear;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__counter__DOT__clock;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__counter__DOT__clear;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__btn_left;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__btn_right;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__btn_up;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__btn_down;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__clk;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__reset;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__clear;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__counter__DOT__clock;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__counter__DOT__clear;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__btn_left;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__btn_right;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__btn_up;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__btn_down;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__clk;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__reset;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__clear;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__counter__DOT__clock;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__counter__DOT__clear;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__wait_time__DOT__clock;
        CData/*0:0*/ ChipInterface__DOT__simulator__DOT__wait_time__DOT__clear;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__ChipInterface__DOT__clk10__0;
        CData/*0:0*/ __VactContinue;
        SData/*8:0*/ ChipInterface__DOT__led_module__DOT__ws__DOT__led_index;
        SData/*14:0*/ ChipInterface__DOT__simulator__DOT__wait_idx;
    };
    struct {
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__x0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__y0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__m0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__vx0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__vy0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__x1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__y1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__m1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__vx1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__vy1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__x2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__y2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__m2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__vx2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__vy2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__x;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__y;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__m;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__vel_x;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__vel_y;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__px;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__py;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__px_old;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__py_old;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__vx;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__vy;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__ax;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__ay;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__force_x;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__force_y;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__dx0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__dy0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__dx1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__dy1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__dx2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__dy2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__d0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__d1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__d2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__displace0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__displace1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__displace2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__rel_vel_x0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__rel_vel_x1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__rel_vel_x2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__rel_vel_y0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__rel_vel_y1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__rel_vel_y2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__dampx0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__dampx1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__dampx2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__dampy0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__dampy1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__dampy2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__damp0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__damp1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__damp2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__multa;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__multb;
        SData/*14:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__idx;
        SData/*14:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__counter__DOT__Q;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__x0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__y0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__m0;
    };
    struct {
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__vx0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__vy0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__x1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__y1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__m1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__vx1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__vy1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__x2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__y2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__m2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__vx2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__vy2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__x;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__y;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__m;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__vel_x;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__vel_y;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__px;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__py;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__px_old;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__py_old;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__vx;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__vy;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__ax;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__ay;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__force_x;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__force_y;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__dx0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__dy0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__dx1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__dy1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__dx2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__dy2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__d0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__d1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__d2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__displace0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__displace1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__displace2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__rel_vel_x0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__rel_vel_x1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__rel_vel_x2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__rel_vel_y0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__rel_vel_y1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__rel_vel_y2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__dampx0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__dampx1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__dampx2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__dampy0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__dampy1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__dampy2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__damp0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__damp1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__damp2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__multa;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__multb;
        SData/*14:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__idx;
        SData/*14:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__counter__DOT__Q;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__x0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__y0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__m0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__vx0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__vy0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__x1;
    };
    struct {
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__y1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__m1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__vx1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__vy1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__x2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__y2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__m2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__vx2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__vy2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__x;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__y;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__m;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__vel_x;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__vel_y;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__px;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__py;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__px_old;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__py_old;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__vx;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__vy;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__ax;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__ay;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__force_x;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__force_y;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__dx0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__dy0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__dx1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__dy1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__dx2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__dy2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__d0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__d1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__d2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__displace0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__displace1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__displace2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__rel_vel_x0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__rel_vel_x1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__rel_vel_x2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__rel_vel_y0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__rel_vel_y1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__rel_vel_y2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__dampx0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__dampx1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__dampx2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__dampy0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__dampy1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__dampy2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__damp0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__damp1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__damp2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__multa;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__multb;
        SData/*14:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__idx;
        SData/*14:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__counter__DOT__Q;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__x0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__y0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__m0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__vx0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__vy0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__x1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__y1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__m1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__vx1;
    };
    struct {
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__vy1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__x2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__y2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__m2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__vx2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__vy2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__x;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__y;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__m;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__vel_x;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__vel_y;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__px;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__py;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__px_old;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__py_old;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__vx;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__vy;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__ax;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__ay;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__force_x;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__force_y;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__dx0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__dy0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__dx1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__dy1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__dx2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__dy2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__d0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__d1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__d2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__displace0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__displace1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__displace2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__rel_vel_x0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__rel_vel_x1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__rel_vel_x2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__rel_vel_y0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__rel_vel_y1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__rel_vel_y2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__dampx0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__dampx1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__dampx2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__dampy0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__dampy1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__dampy2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__damp0;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__damp1;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__damp2;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__multa;
        SData/*15:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__multb;
        SData/*14:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__idx;
        SData/*14:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__counter__DOT__Q;
        SData/*14:0*/ ChipInterface__DOT__simulator__DOT__wait_time__DOT__Q;
        VlWide<3>/*95:0*/ ChipInterface__DOT__data;
        VlWide<8>/*255:0*/ ChipInterface__DOT__matrix;
        VlWide<3>/*95:0*/ ChipInterface__DOT__led_module__DOT__imu_data;
        VlWide<8>/*255:0*/ ChipInterface__DOT__led_module__DOT__matrix;
        VlWide<192>/*6143:0*/ ChipInterface__DOT__led_module__DOT__data;
        IData/*31:0*/ ChipInterface__DOT__led_module__DOT__sv2v_autoblock_1__DOT__start;
        IData/*31:0*/ ChipInterface__DOT__led_module__DOT__sv2v_autoblock_1__DOT__sv2v_autoblock_2__DOT__led_idx;
        IData/*31:0*/ ChipInterface__DOT__led_module__DOT__sv2v_autoblock_1__DOT__sv2v_autoblock_3__DOT__led_idx;
        VlWide<192>/*6143:0*/ ChipInterface__DOT__led_module__DOT__ws__DOT__data;
        VlWide<192>/*6143:0*/ ChipInterface__DOT__led_module__DOT__ws__DOT__data_int;
        IData/*17:0*/ ChipInterface__DOT__led_module__DOT__ws__DOT__latch_ctr;
    };
    struct {
        IData/*23:0*/ ChipInterface__DOT__led_module__DOT__ws__DOT__cur_led_dat;
        VlWide<3>/*95:0*/ ChipInterface__DOT__sensor__DOT__curr_data;
        VlWide<3>/*95:0*/ ChipInterface__DOT__sensor__DOT__next_data;
        IData/*20:0*/ ChipInterface__DOT__sensor__DOT__wait_idx;
        IData/*20:0*/ ChipInterface__DOT__sensor__DOT__wait_time__DOT__Q;
        VlWide<3>/*95:0*/ ChipInterface__DOT__simulator__DOT__data;
        VlWide<8>/*255:0*/ ChipInterface__DOT__simulator__DOT__matrix;
        VlWide<8>/*255:0*/ ChipInterface__DOT__simulator__DOT__next_matrix;
        IData/*31:0*/ ChipInterface__DOT__simulator__DOT__cx;
        IData/*31:0*/ ChipInterface__DOT__simulator__DOT__cy;
        IData/*31:0*/ ChipInterface__DOT__simulator__DOT__cm;
        IData/*31:0*/ ChipInterface__DOT__simulator__DOT__cvx;
        IData/*31:0*/ ChipInterface__DOT__simulator__DOT__cvy;
        IData/*31:0*/ ChipInterface__DOT__simulator__DOT__p0x;
        IData/*31:0*/ ChipInterface__DOT__simulator__DOT__p0y;
        IData/*31:0*/ ChipInterface__DOT__simulator__DOT__p0m;
        IData/*31:0*/ ChipInterface__DOT__simulator__DOT__p0vx;
        IData/*31:0*/ ChipInterface__DOT__simulator__DOT__p0vy;
        IData/*31:0*/ ChipInterface__DOT__simulator__DOT__p1x;
        IData/*31:0*/ ChipInterface__DOT__simulator__DOT__p1y;
        IData/*31:0*/ ChipInterface__DOT__simulator__DOT__p1m;
        IData/*31:0*/ ChipInterface__DOT__simulator__DOT__p1vx;
        IData/*31:0*/ ChipInterface__DOT__simulator__DOT__p1vy;
        IData/*31:0*/ ChipInterface__DOT__simulator__DOT__p2x;
        IData/*31:0*/ ChipInterface__DOT__simulator__DOT__p2y;
        IData/*31:0*/ ChipInterface__DOT__simulator__DOT__p2m;
        IData/*31:0*/ ChipInterface__DOT__simulator__DOT__p2vx;
        IData/*31:0*/ ChipInterface__DOT__simulator__DOT__p2vy;
        IData/*31:0*/ ChipInterface__DOT__simulator__DOT__sv2v_autoblock_1__DOT__y;
        IData/*31:0*/ ChipInterface__DOT__simulator__DOT__sv2v_autoblock_1__DOT__sv2v_autoblock_2__DOT__x;
        IData/*31:0*/ __VactIterCount;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<2> __VactTriggered;
    VlTriggerVec<2> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr IData/*31:0*/ ChipInterface__DOT__led_module__DOT__CLK_FREQ = 0x01312d00U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__led_module__DOT__NUM_LEDS = 0x00000100U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__led_module__DOT__NUM_FRAMES = 1U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__led_module__DOT__ws__DOT__NUM_LEDS = 0x00000100U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__led_module__DOT__ws__DOT__CLK_FREQ = 0x01312d00U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__led_module__DOT__ws__DOT__T0H = 8U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__led_module__DOT__ws__DOT__T1H = 0x00000010U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__led_module__DOT__ws__DOT__T0L = 0x00000011U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__led_module__DOT__ws__DOT__T1L = 9U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__led_module__DOT__ws__DOT__LATCH_TIME = 0x00000fa0U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__led_module__DOT__ws__DOT__PULSE_WIDTH = 0x00000019U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__sensor__DOT__WAIT_CYCLES = 0x000f4240U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__sensor__DOT__wait_time__DOT__WIDTH = 0x00000015U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__WAIT_CYCLES = 0x00002710U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__MASS = 0x00000010U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__INIT_X = 0x00000080U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__INIT_Y = 0x00000080U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__REST0 = 0x00000020U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__REST1 = 0x00000020U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__REST2 = 0x00000020U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__PHASE_OFFSET = 0U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__WIDTH = 0x00000100U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__SPRING = 8U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__DAMPING = 4U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__TIME_STEP = 2U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__FORCE_MAG = 0x00000020U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__TOTAL_CYCLES = 0x00002710U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__center__DOT__counter__DOT__WIDTH = 0x0000000fU;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__MASS = 8U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__INIT_X = 0x00000080U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__INIT_Y = 0x00000060U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__REST0 = 0x00000020U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__REST1 = 0x00000047U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__REST2 = 0x00000047U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__PHASE_OFFSET = 0x00000064U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__WIDTH = 0x00000100U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__SPRING = 8U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__DAMPING = 4U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__TIME_STEP = 2U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__FORCE_MAG = 0x00000020U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__TOTAL_CYCLES = 0x00002710U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral0__DOT__counter__DOT__WIDTH = 0x0000000fU;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__MASS = 8U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__INIT_X = 0x00000060U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__INIT_Y = 0x000000a0U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__REST0 = 0x00000047U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__REST1 = 0x00000020U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__REST2 = 0x00000047U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__PHASE_OFFSET = 0x000000c8U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__WIDTH = 0x00000100U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__SPRING = 8U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__DAMPING = 4U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__TIME_STEP = 2U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__FORCE_MAG = 0x00000020U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__TOTAL_CYCLES = 0x00002710U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral1__DOT__counter__DOT__WIDTH = 0x0000000fU;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__MASS = 8U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__INIT_X = 0x000000a0U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__INIT_Y = 0x000000a0U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__REST0 = 0x00000047U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__REST1 = 0x00000047U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__REST2 = 0x00000020U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__PHASE_OFFSET = 0x0000012cU;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__WIDTH = 0x00000100U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__SPRING = 8U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__DAMPING = 4U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__TIME_STEP = 2U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__FORCE_MAG = 0x00000020U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__TOTAL_CYCLES = 0x00002710U;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__peripheral2__DOT__counter__DOT__WIDTH = 0x0000000fU;
    static constexpr IData/*31:0*/ ChipInterface__DOT__simulator__DOT__wait_time__DOT__WIDTH = 0x0000000fU;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
